---
openapi: 3.0.0
info:
  title: API V1
  version: v1
paths:
  "/content/show":
    get:
      summary: Retorna as informações do sistema
      tags:
      - Content
      description: Modelo de documentação para APIs contendo as informações da rota
      responses:
        '200':
          description: Data returned
  "/user/login":
    post:
      summary: Efetua login e gera chave criptografada
      tags:
      - User
      description: Endpoint para gerar chave criptografada de login
      parameters: []
      responses:
        '200':
          description: Login Efetuado Com Sucesso!
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      example: kaineo@hotmail.com
                    password:
                      type: string
                      example: qwe123
              required:
              - email
              - password
  "/user/create":
    post:
      summary: Cria usuário
      tags:
      - User
      description: Endpoint para criar usuário
      parameters: []
      responses:
        '201':
          description: Usuário Criado Com Sucesso!
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Caio Ramos
                    email:
                      type: string
                      example: kaineo@hotmail.com
                    password:
                      type: string
                      example: qwe123
              required:
              - name
              - email
              - password
  "/user/update":
    patch:
      summary: Atualiza usuário a partir do token gerado no login
      tags:
      - User
      security:
      - Bearer: {}
      description: Endpoint para alterar usuário
      parameters: []
      responses:
        '200':
          description: Usuário Criado Com Sucesso!
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Caio Ramos
                    email:
                      type: string
                      example: kaineo@hotmail.com
                    password:
                      type: string
                      example: qwe123
              required:
              - name
              - email
              - password
  "/user/show":
    get:
      summary: Exibe usuário a partir do token gerado no login
      tags:
      - User
      security:
      - Bearer: {}
      description: Endpoint para mostrar dados do usuário logado
      responses:
        '200':
          description: Informações de Usuário Exibidas Com Sucesso!
components:
  securitySchemes:
    Bearer:
      description: Chave JWT requerida
      type: apiKey
      name: Authorization
      in: header
