default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: pguser
  password: postgres

development:
  <<: *default
  database: app_development
  host: <%= ENV['DB_HOST'] %>

test:
  <<: *default
  database: app_test
  host: <%= ENV['DB_HOST'] %>

production:
  <<: *default
  database: app_production
  username: app
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
